### ISSUE TITLE
No Readme.md file available

### ISSUE THREAD

**Issue by stealthman22** [python-poetry/poetry-core#2]
Hello.
Please without a read me, we will have no idea what this project is about.
It Would be nice to add one.

**Comment by boukeversteegh** [comment]
Hesitant to use this package as our build backend without any documentation. Thanks!

**Comment by FredHappyface** [comment]
So to clarify is this project solely for building poetry or can it be used by third parties? 

Is it planned for instance to outline what functionality is covered here and what is covered by poetry 'full'?

Cheers

**Comment by abn** [comment]
@FredHappyface I have added some information in #66. This package is intended to be a build backend fully compliant with PEP 517. Some shared functionality like configuration/`pyproject.toml`/`poetry.lock` parsing will also be available here. Poetry itself will use this package for everythign that is implemented here.

Right now, we do not intend formalise a public API other than what is required for PEP 517. But we do want to make things more accessible for downstream developers so they don't have to reinvent the wheel when building poetry plugins etc.
