### ISSUE TITLE
Change default sdist tarfile format from PAX_FORMAT to GNU_FORMAT

### ISSUE THREAD

**Issue by bbeattie-phxlabs** [python-poetry/poetry-core#296]
https://github.com/python-poetry/poetry-core/blob/4e5207e4d41c0c4f1844b1389eef79276af47a49/src/poetry/core/masonry/builders/sdist.py#L72 instructs tarfile to use `PAX_FORMAT`.

https://serverfault.com/a/953096 reveals its non-deterministic nature (two identical builds of the same package will produce tgz files with different hashes).

Given that https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT changed from PAX_FORMAT to GNU_FORMAT in Python 3.8, might we consider changing poetry-core's tarfile format as well?

**Comment by koyeung** [comment]
Should it be change from `GNU_FORMAT` to `PAX_FORMAT` in python 3.8?

https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT

**Comment by bbeattie-phxlabs** [comment]
Ah-hah. I misread and it's the other way around.
